name: repurpose-bc
channels: [conda-forge, defaults]
dependencies:
  - python=3.10
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - pyarrow>=14.0
  - scikit-learn>=1.3
  - xgboost>=1.7
  - matplotlib>=3.8
  - seaborn>=0.12
  - networkx>=3.2
  - tqdm>=4.66
  - pyyaml>=6.0
  - requests>=2.31
  - tabulate>=0.9
  - joblib>=1.3
  - pip
  - pip:
      # keep empty unless you truly need a pip-only library
      # - some-pip-only-package==x.y.z
